In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

# Using Classifiers on iris

## KNN (k_nearest_neighbors)

In [2]:
from sklearn.neighbors import KNeighborsClassifier

In [3]:
iris=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\iris.csv")
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
x = iris.drop('Species', axis=1)
y = iris['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

#### Making Model

In [5]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

#### Checking accuracy with confusion matrix and accuracy score

In [6]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0


## Logistic Regression

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
iris=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\iris.csv")
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
virginica = iris[iris['Species']=='virginica']

iris = iris.drop(virginica.index)

In [10]:
iris['Species'].unique()

array(['setosa', 'versicolor'], dtype=object)

In [11]:
x = iris.drop('Species', axis=1)
y = iris['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

#### Making Model

In [12]:
lrr = LogisticRegression(random_state=1)
lrr.fit(x_train, y_train)

LogisticRegression(random_state=1)

#### Checking accuracy with confusion matrix and accuracy score

In [13]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 8  0]
 [ 0 12]]
1.0


## Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB

In [15]:
iris=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\iris.csv")
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
x = iris.drop('Species', axis=1)
y = iris['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

#### Making Model

In [17]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

#### Checking accuracy with confusion matrix and accuracy score

In [18]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0


<h2>
    Using Iris data set, apply Naïve bays theorem and KNN algorithm, and find 
    accuracy of the model
</h2>

In [19]:
iris=pd.read_csv(r"C:\Users\patil\Desktop\Know IT CADC\Adv Analytics\Datasets\iris.csv")
iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## KNN (k_nearest_neighbors)

In [20]:
x = iris.drop('Species', axis=1)
y = iris['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

In [21]:
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [22]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0


## Naive Bayes

In [23]:
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [24]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
1.0


<h2>
    2. From Iris dataset keep rows with values Setosa-virginica and setosa-bersicolor, 
    and apply logistic-regression algorithm and find accuracy score.


</h2>

## Setosa Versicolor

In [25]:
iris1 = iris

In [26]:
virginica = iris1[iris1['Species']=='virginica']

iris1 = iris1.drop(virginica.index)

In [27]:
x = iris1.drop('Species', axis=1)
y = iris1['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

In [28]:
lrr = LogisticRegression(random_state=1)
lrr.fit(x_train, y_train)

LogisticRegression(random_state=1)

In [29]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 8  0]
 [ 0 12]]
1.0


## Setosa Virginica

In [30]:
iris1 = iris

In [31]:
virginica = iris1[iris1['Species']=='versicolor']

iris1 = iris1.drop(virginica.index)

In [32]:
x = iris1.drop('Species', axis=1)
y = iris1['Species']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.2)

In [33]:
lrr = LogisticRegression(random_state=1)
lrr.fit(x_train, y_train)

LogisticRegression(random_state=1)

In [34]:
y_pred = classifier.predict(x_test)

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[ 8  0  0]
 [ 0  0  0]
 [ 0  2 10]]
0.9
